sudo: required
language: node_js
node_js:
  - 0.10

install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ wily universe"
  - sudo apt-get update -q
  - sudo apt-get install shellcheck -y

script:
  - shellcheck -s-shell=zsh bullet-train.zsh-theme
